#!/usr/bin/env node
/**
 * Writes .env.local from Supabase credentials.
 *
 * Usage:
 *   npm run setup
 *   npm run setup -- https://xxx.supabase.co eyJ...
 *   SUPABASE_URL=... SUPABASE_ANON_KEY=... npm run setup
 */

import { writeFileSync } from 'node:fs';
import { createInterface } from 'node:readline';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const ENV_PATH = resolve(ROOT, '.env.local');

function prompt(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolvePrompt) => {
    rl.question(question, (answer) => {
      rl.close();
      resolvePrompt(answer.trim());
    });
  });
}

async function main() {
  const urlFromArgs = process.argv[2];
  const keyFromArgs = process.argv[3];

  const supabaseUrl =
    urlFromArgs || process.env.SUPABASE_URL || (await prompt('Supabase URL: '));
  const anonKey =
    keyFromArgs || process.env.SUPABASE_ANON_KEY || (await prompt('Anon Key: '));

  if (!supabaseUrl || !anonKey) {
    console.error('URL und Anon Key sind erforderlich.');
    process.exit(1);
  }

  const contents = `# Generated by npm run setup — ${new Date().toISOString()}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
`;

  writeFileSync(ENV_PATH, contents, 'utf8');
  console.log(`✓ ${ENV_PATH} geschrieben`);
  console.log('  Dev-Server neu starten: npm run dev');
  console.log('  Migrationen (falls noch nicht): npm run db:push');
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
